In [51]:
import numpy as np
import pandas as pd

In [52]:
print("NumPy Version:", np.__version__)
print("Pandas Version:", pd.__version__)

NumPy Version: 2.4.4
Pandas Version: 3.0.2

In [53]:
data = {
    "Student_ID": [
        "S001", "S002", "S003", "S004", "S005",
        "S006", "S007", "S008", "S009", "S010",
        "S011", "S012", "S013", "S014", "S015",
        "S016", "S017", "S018", "S019", "S020"
    ],

    "Name": [
        "Aarav Sharma", "Priya Singh", "Rahul Verma", "Sneha Patel",
        "Aditya Kumar", "Ananya Gupta", "Rohan Mehta", "Neha Joshi",
        "Vivek Shah", "Kavya Jain", "Arjun Rao", "Simran Kaur",
        "Yash Malhotra", "Isha Agarwal", "Karan Mishra",
        "Riya Kapoor", "Manish Yadav", "Pooja Nair", "Dev Tiwari",
        "Nisha Saxena"
    ],

    "Department": [
        "CSE", "CSE", "IT", "CSE", "IT",
        "CSE", "IT", "CSE", "IT", "CSE",
        "IT", "CSE", "IT", "CSE", "IT",
        "CSE", "IT", "CSE", "IT", "CSE"
    ],

    "Python": [
        88, 76, 65, 92, 58,
        81, 73, 95, 67, 84,
        72, 89, 61, 78, 55,
        91, 69, 83, 47, 74
    ],

    "AI": [
        91, 82, 70, 89, 62,
        85, 77, 93, 64, 80,
        75, 87, 59, 81, 52,
        94, 68, 86, 45, 71
    ],

    "Mathematics": [
        85, 79, 68, 94, 55,
        78, 80, 91, 70, 82,
        69, 90, 63, 76, 57,
        89, 72, 84, 49, 73
    ],

    "Attendance": [
        92, 88, 75, 96, 72,
        85, 91, 94, 78, 89,
        82, 95, 70, 87, 68,
        97, 76, 90, 65, 84
    ]
}

df = pd.DataFrame(data)

df

   Student_ID           Name Department  Python  AI  Mathematics  Attendance
0        S001   Aarav Sharma        CSE      88  91           85          92
1        S002    Priya Singh        CSE      76  82           79          88
2        S003    Rahul Verma         IT      65  70           68          75
3        S004    Sneha Patel        CSE      92  89           94          96
4        S005   Aditya Kumar         IT      58  62           55          72
5        S006   Ananya Gupta        CSE      81  85           78          85
6        S007    Rohan Mehta         IT      73  77           80          91
7        S008     Neha Joshi        CSE      95  93           91          94
8        S009     Vivek Shah         IT      67  64           70          78
9        S010     Kavya Jain        CSE      84  80           82          89
10       S011      Arjun Rao         IT      72  75           69          82
11       S012    Simran Kaur        CSE      89  87           90          95
12       S013  Yash Malhotra         IT      61  59           63          70
13       S014   Isha Agarwal        CSE      78  81           76          87
14       S015   Karan Mishra         IT      55  52           57          68
15       S016    Riya Kapoor        CSE      91  94           89          97
16       S017   Manish Yadav         IT      69  68           72          76
17       S018     Pooja Nair        CSE      83  86           84          90
18       S019     Dev Tiwari         IT      47  45           49          65
19       S020   Nisha Saxena        CSE      74  71           73          84

In [54]:
df.to_csv("students.csv", index=False)

print("Dataset saved successfully as students.csv")

Dataset saved successfully as students.csv

In [55]:
df = pd.read_csv("students.csv")
df.head()

  Student_ID          Name Department  Python  AI  Mathematics  Attendance
0       S001  Aarav Sharma        CSE      88  91           85          92
1       S002   Priya Singh        CSE      76  82           79          88
2       S003   Rahul Verma         IT      65  70           68          75
3       S004   Sneha Patel        CSE      92  89           94          96
4       S005  Aditya Kumar         IT      58  62           55          72

In [56]:
print("Number of students:", len(df))
print("Number of columns:", len(df.columns))

Number of students: 20
Number of columns: 7

In [57]:
print("Columns in dataset:")
print(df.columns.tolist())

Columns in dataset:
['Student_ID', 'Name', 'Department', 'Python', 'AI', 'Mathematics', 'Attendance']

In [58]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Student_ID   20 non-null     str
 1   Name         20 non-null     str
 2   Department   20 non-null     str
 3   Python       20 non-null     int64
 4   AI           20 non-null     int64
 5   Mathematics  20 non-null     int64
 6   Attendance   20 non-null     int64
dtypes: int64(4), str(3)
memory usage: 1.2 KB

In [59]:
df.describe()

          Python         AI  Mathematics  Attendance
count  20.000000  20.000000    20.000000   20.000000
mean   74.900000  75.550000    75.200000   83.700000
std    13.345214  13.907495    12.534584    9.931873
min    47.000000  45.000000    49.000000   65.000000
25%    66.500000  67.000000    68.750000   75.750000
50%    75.000000  78.500000    77.000000   86.000000
75%    85.000000  86.250000    84.250000   91.250000
max    95.000000  94.000000    94.000000   97.000000

In [60]:
print("Missing values in each column:")
print(df.isnull().sum())

Missing values in each column:
Student_ID     0
Name           0
Department     0
Python         0
AI             0
Mathematics    0
Attendance     0
dtype: int64

In [61]:
print("Number of duplicate records:", df.duplicated().sum())

Number of duplicate records: 0

In [62]:
df["Total_Marks"] = (
    df["Python"] +
    df["AI"] +
    df["Mathematics"]
)
df[["Student_ID", "Name", "Python", "AI", "Mathematics", "Total_Marks"]]

   Student_ID           Name  Python  AI  Mathematics  Total_Marks
0        S001   Aarav Sharma      88  91           85          264
1        S002    Priya Singh      76  82           79          237
2        S003    Rahul Verma      65  70           68          203
3        S004    Sneha Patel      92  89           94          275
4        S005   Aditya Kumar      58  62           55          175
5        S006   Ananya Gupta      81  85           78          244
6        S007    Rohan Mehta      73  77           80          230
7        S008     Neha Joshi      95  93           91          279
8        S009     Vivek Shah      67  64           70          201
9        S010     Kavya Jain      84  80           82          246
10       S011      Arjun Rao      72  75           69          216
11       S012    Simran Kaur      89  87           90          266
12       S013  Yash Malhotra      61  59           63          183
13       S014   Isha Agarwal      78  81           76          235
14       S015   Karan Mishra      55  52           57          164
15       S016    Riya Kapoor      91  94           89          274
16       S017   Manish Yadav      69  68           72          209
17       S018     Pooja Nair      83  86           84          253
18       S019     Dev Tiwari      47  45           49          141
19       S020   Nisha Saxena      74  71           73          218

In [63]:
highest_total = np.max(df["Total_Marks"])
print("Highest Total Marks:", highest_total)

Highest Total Marks: 279

In [64]:
lowest_total = np.min(df["Total_Marks"])
print("Lowest Total Marks:", lowest_total)

Lowest Total Marks: 141

In [65]:
class_average = np.mean(df["Total_Marks"])
print("Class Average Total Marks:", round(class_average, 2))

Class Average Total Marks: 225.65

In [66]:
df["Average_Marks"] = df["Total_Marks"] / 3
df[["Student_ID", "Name", "Total_Marks", "Average_Marks"]]

   Student_ID           Name  Total_Marks  Average_Marks
0        S001   Aarav Sharma          264      88.000000
1        S002    Priya Singh          237      79.000000
2        S003    Rahul Verma          203      67.666667
3        S004    Sneha Patel          275      91.666667
4        S005   Aditya Kumar          175      58.333333
5        S006   Ananya Gupta          244      81.333333
6        S007    Rohan Mehta          230      76.666667
7        S008     Neha Joshi          279      93.000000
8        S009     Vivek Shah          201      67.000000
9        S010     Kavya Jain          246      82.000000
10       S011      Arjun Rao          216      72.000000
11       S012    Simran Kaur          266      88.666667
12       S013  Yash Malhotra          183      61.000000
13       S014   Isha Agarwal          235      78.333333
14       S015   Karan Mishra          164      54.666667
15       S016    Riya Kapoor          274      91.333333
16       S017   Manish Yadav          209      69.666667
17       S018     Pooja Nair          253      84.333333
18       S019     Dev Tiwari          141      47.000000
19       S020   Nisha Saxena          218      72.666667

In [67]:
df["Average_Marks"] = df["Average_Marks"].round(2)
df[["Student_ID", "Name", "Average_Marks"]]

   Student_ID           Name  Average_Marks
0        S001   Aarav Sharma          88.00
1        S002    Priya Singh          79.00
2        S003    Rahul Verma          67.67
3        S004    Sneha Patel          91.67
4        S005   Aditya Kumar          58.33
5        S006   Ananya Gupta          81.33
6        S007    Rohan Mehta          76.67
7        S008     Neha Joshi          93.00
8        S009     Vivek Shah          67.00
9        S010     Kavya Jain          82.00
10       S011      Arjun Rao          72.00
11       S012    Simran Kaur          88.67
12       S013  Yash Malhotra          61.00
13       S014   Isha Agarwal          78.33
14       S015   Karan Mishra          54.67
15       S016    Riya Kapoor          91.33
16       S017   Manish Yadav          69.67
17       S018     Pooja Nair          84.33
18       S019     Dev Tiwari          47.00
19       S020   Nisha Saxena          72.67

In [68]:
def assign_grade(average):
    if average >= 90:
        return "A+"
    elif average >= 80:
        return "A"
    elif average >= 70:
        return "B"
    elif average >= 60:
        return "C"
    elif average >= 50:
        return "D"
    else:
        return "F"

In [69]:
grades = []
for average in df["Average_Marks"]:
    grade = assign_grade(average)
    grades.append(grade)
df["Grade"] = grades
df[["Student_ID", "Name", "Average_Marks", "Grade"]]

   Student_ID           Name  Average_Marks Grade
0        S001   Aarav Sharma          88.00     A
1        S002    Priya Singh          79.00     B
2        S003    Rahul Verma          67.67     C
3        S004    Sneha Patel          91.67    A+
4        S005   Aditya Kumar          58.33     D
5        S006   Ananya Gupta          81.33     A
6        S007    Rohan Mehta          76.67     B
7        S008     Neha Joshi          93.00    A+
8        S009     Vivek Shah          67.00     C
9        S010     Kavya Jain          82.00     A
10       S011      Arjun Rao          72.00     B
11       S012    Simran Kaur          88.67     A
12       S013  Yash Malhotra          61.00     C
13       S014   Isha Agarwal          78.33     B
14       S015   Karan Mishra          54.67     D
15       S016    Riya Kapoor          91.33    A+
16       S017   Manish Yadav          69.67     C
17       S018     Pooja Nair          84.33     A
18       S019     Dev Tiwari          47.00     F
19       S020   Nisha Saxena          72.67     B

In [70]:
print("Number of students:", len(df))
print("Number of grades:", len(grades))

Number of students: 20
Number of grades: 20

In [71]:
def check_pass_fail(average):
    if average >= 40:
        return "PASS"
    else:
        return "FAIL"

In [72]:
results = []
for average in df["Average_Marks"]:
    result = check_pass_fail(average)
    results.append(result)
df["Result"] = results
df[["Student_ID", "Name", "Average_Marks", "Grade", "Result"]]

   Student_ID           Name  Average_Marks Grade Result
0        S001   Aarav Sharma          88.00     A   PASS
1        S002    Priya Singh          79.00     B   PASS
2        S003    Rahul Verma          67.67     C   PASS
3        S004    Sneha Patel          91.67    A+   PASS
4        S005   Aditya Kumar          58.33     D   PASS
5        S006   Ananya Gupta          81.33     A   PASS
6        S007    Rohan Mehta          76.67     B   PASS
7        S008     Neha Joshi          93.00    A+   PASS
8        S009     Vivek Shah          67.00     C   PASS
9        S010     Kavya Jain          82.00     A   PASS
10       S011      Arjun Rao          72.00     B   PASS
11       S012    Simran Kaur          88.67     A   PASS
12       S013  Yash Malhotra          61.00     C   PASS
13       S014   Isha Agarwal          78.33     B   PASS
14       S015   Karan Mishra          54.67     D   PASS
15       S016    Riya Kapoor          91.33    A+   PASS
16       S017   Manish Yadav          69.67     C   PASS
17       S018     Pooja Nair          84.33     A   PASS
18       S019     Dev Tiwari          47.00     F   PASS
19       S020   Nisha Saxena          72.67     B   PASS

In [73]:
pass_count = (df["Result"] == "PASS").sum()
fail_count = (df["Result"] == "FAIL").sum()
print("Number of students passed:", pass_count)
print("Number of students failed:", fail_count)

Number of students passed: 20
Number of students failed: 0

In [74]:
highest_index = df["Average_Marks"].idxmax()
highest_student = df.loc[highest_index]
print("Highest Performing Student")
print("--------------------------")
print("Student ID:", highest_student["Student_ID"])
print("Name:", highest_student["Name"])
print("Average Marks:", highest_student["Average_Marks"])
print("Grade:", highest_student["Grade"])

Highest Performing Student
--------------------------
Student ID: S008
Name: Neha Joshi
Average Marks: 93.0
Grade: A+

In [75]:
lowest_index = df["Average_Marks"].idxmin()
lowest_student = df.loc[lowest_index]
print("Lowest Performing Student")
print("-------------------------")
print("Student ID:", lowest_student["Student_ID"])
print("Name:", lowest_student["Name"])
print("Average Marks:", lowest_student["Average_Marks"])
print("Grade:", lowest_student["Grade"])

Lowest Performing Student
-------------------------
Student ID: S019
Name: Dev Tiwari
Average Marks: 47.0
Grade: F

In [76]:
overall_average = np.mean(df["Average_Marks"])
print("Overall Class Average:", round(overall_average, 2))

Overall Class Average: 75.22

In [77]:
top_students = df.sort_values(
    by="Average_Marks",
    ascending=False
).head(5)
print("Top 5 Performing Students")
print("-------------------------")
print(
    top_students[
        ["Student_ID", "Name", "Average_Marks", "Grade"]
    ].to_string(index=False)
)

Top 5 Performing Students
-------------------------
Student_ID         Name  Average_Marks Grade
      S008   Neha Joshi          93.00    A+
      S004  Sneha Patel          91.67    A+
      S016  Riya Kapoor          91.33    A+
      S012  Simran Kaur          88.67     A
      S001 Aarav Sharma          88.00     A

In [78]:
python_average = np.mean(df["Python"])
ai_average = np.mean(df["AI"])
math_average = np.mean(df["Mathematics"])
print("Subject-wise Average Marks")
print("--------------------------")
print("Python      :", round(python_average, 2))
print("AI          :", round(ai_average, 2))
print("Mathematics :", round(math_average, 2))

Subject-wise Average Marks
--------------------------
Python      : 74.9
AI          : 75.55
Mathematics : 75.2

In [79]:
subject_summary = pd.DataFrame({
    "Subject": ["Python", "AI", "Mathematics"],
    "Average_Marks": [
        python_average,
        ai_average,
        math_average
    ]
})
subject_summary["Average_Marks"] = subject_summary["Average_Marks"].round(2)
subject_summary

       Subject  Average_Marks
0       Python          74.90
1           AI          75.55
2  Mathematics          75.20

In [80]:
best_subject_index = subject_summary["Average_Marks"].idxmax()
weakest_subject_index = subject_summary["Average_Marks"].idxmin()
best_subject = subject_summary.loc[best_subject_index]
weakest_subject = subject_summary.loc[weakest_subject_index]
print("Best Subject:")
print(
    best_subject["Subject"],
    "-",
    best_subject["Average_Marks"]
)
print("\nWeakest Subject:")
print(
    weakest_subject["Subject"],
    "-",
    weakest_subject["Average_Marks"]
)

Best Subject:
AI - 75.55

Weakest Subject:
Python - 74.9

In [81]:
average_attendance = np.mean(df["Attendance"])
print("Average Attendance:", round(average_attendance, 2), "%")

Average Attendance: 83.7 %

In [82]:
low_attendance_students = df[df["Attendance"] < 75]
print("Students with Attendance Below 75%")
print("----------------------------------")
print(
    low_attendance_students[
        ["Student_ID", "Name", "Attendance"]
    ].to_string(index=False)
)

Students with Attendance Below 75%
----------------------------------
Student_ID          Name  Attendance
      S005  Aditya Kumar          72
      S013 Yash Malhotra          70
      S015  Karan Mishra          68
      S019    Dev Tiwari          65

In [83]:
low_attendance_students = df[df["Attendance"] < 75]
print("Students with Attendance Below 75%")
print("----------------------------------")
print(
    low_attendance_students[
        ["Student_ID", "Name", "Attendance"]
    ].to_string(index=False)
)

Students with Attendance Below 75%
----------------------------------
Student_ID          Name  Attendance
      S005  Aditya Kumar          72
      S013 Yash Malhotra          70
      S015  Karan Mishra          68
      S019    Dev Tiwari          65

In [84]:
highest_attendance_index = df["Attendance"].idxmax()
highest_attendance_student = df.loc[highest_attendance_index]
print("Highest Attendance")
print("------------------")
print("Student ID:", highest_attendance_student["Student_ID"])
print("Name:", highest_attendance_student["Name"])
print("Attendance:", highest_attendance_student["Attendance"], "%")

Highest Attendance
------------------
Student ID: S016
Name: Riya Kapoor
Attendance: 97 %

In [85]:
department_average = df.groupby("Department")["Average_Marks"].mean().round(2)
print("Department-wise Average Marks")
print("-----------------------------")
print(department_average)

Department-wise Average Marks
-----------------------------
Department
CSE    84.58
IT     63.78
Name: Average_Marks, dtype: float64

In [86]:
best_department = department_average.idxmax()
best_department_average = department_average.max()
print("Best Performing Department:", best_department)
print("Average Marks:", best_department_average)

Best Performing Department: CSE
Average Marks: 84.58

In [87]:
department_count = df["Department"].value_counts()
print("Number of Students in Each Department")
print("--------------------------------------")
print(department_count)

Number of Students in Each Department
--------------------------------------
Department
CSE    11
IT      9
Name: count, dtype: int64

In [88]:
final_summary = df[
    [
        "Student_ID",
        "Name",
        "Department",
        "Total_Marks",
        "Average_Marks",
        "Grade",
        "Result",
        "Attendance"
    ]
]
final_summary

,Student_ID,Name,Department,Total_Marks,Average_Marks,Grade,Result,Attendance
0,S001,Aarav Sharma,CSE,264,88.00,A,PASS,92
1,S002,Priya Singh,CSE,237,79.00,B,PASS,88
2,S003,Rahul Verma,IT,203,67.67,C,PASS,75
3,S004,Sneha Patel,CSE,275,91.67,A+,PASS,96
4,S005,Aditya Kumar,IT,175,58.33,D,PASS,72
5,S006,Ananya Gupta,CSE,244,81.33,A,PASS,85
6,S007,Rohan Mehta,IT,230,76.67,B,PASS,91
7,S008,Neha Joshi,CSE,279,93.00,A+,PASS,94
8,S009,Vivek Shah,IT,201,67.00,C,PASS,78
9,S010,Kavya Jain,CSE,246,82.00,A,PASS,89
10,S011,Arjun Rao,IT,216,72.00,B,PASS,82
11,S012,Simran Kaur,CSE,266,88.67,A,PASS,95
12,S013,Yash Malhotra,IT,183,61.00,C,PASS,70
13,S014,Isha Agarwal,CSE,235,78.33,B,PASS,87
14,S015,Karan Mishra,IT,164,54.67,D,PASS,68
15,S016,Riya Kapoor,CSE,274,91.33,A+,PASS,97
16,S017,Manish Yadav,IT,209,69.67,C,PASS,76
17,S018,Pooja Nair,CSE,253,84.33,A,PASS,90
18,S019,Dev Tiwari,IT,141,47.00,F,PASS,65
19,S020,Nisha Saxena,CSE,218,72.67,B,PASS,84

In [89]:
print("===== TOP 5 PERFORMING STUDENTS =====")
print(
    final_summary
    .sort_values(by="Average_Marks", ascending=False)
    .head(5)
    .to_string(index=False)
)

===== TOP 5 PERFORMING STUDENTS =====
Student_ID         Name Department  Total_Marks  Average_Marks Grade Result  Attendance
      S008   Neha Joshi        CSE          279          93.00    A+   PASS          94
      S004  Sneha Patel        CSE          275          91.67    A+   PASS          96
      S016  Riya Kapoor        CSE          274          91.33    A+   PASS          97
      S012  Simran Kaur        CSE          266          88.67     A   PASS          95
      S001 Aarav Sharma        CSE          264          88.00     A   PASS          92

In [90]:
print("===== OVERALL PERFORMANCE SUMMARY =====")
print("Total Students       :", len(df))
print("Students Passed      :", pass_count)
print("Students Failed      :", fail_count)
print("Highest Total Marks  :", highest_total)
print("Lowest Total Marks   :", lowest_total)
print("Overall Class Average:", round(overall_average, 2))
print("Average Attendance   :", round(average_attendance, 2), "%")

===== OVERALL PERFORMANCE SUMMARY =====
Total Students       : 20
Students Passed      : 20
Students Failed      : 0
Highest Total Marks  : 279
Lowest Total Marks   : 141
Overall Class Average: 75.22
Average Attendance   : 83.7 %

In [91]:
print("===== FINAL STUDENT PERFORMANCE DATA =====")
df

===== FINAL STUDENT PERFORMANCE DATA =====

,Student_ID,Name,Department,Python,AI,Mathematics,Attendance,Total_Marks,Average_Marks,Grade,Result
0,S001,Aarav Sharma,CSE,88,91,85,92,264,88.00,A,PASS
1,S002,Priya Singh,CSE,76,82,79,88,237,79.00,B,PASS
2,S003,Rahul Verma,IT,65,70,68,75,203,67.67,C,PASS
3,S004,Sneha Patel,CSE,92,89,94,96,275,91.67,A+,PASS
4,S005,Aditya Kumar,IT,58,62,55,72,175,58.33,D,PASS
5,S006,Ananya Gupta,CSE,81,85,78,85,244,81.33,A,PASS
6,S007,Rohan Mehta,IT,73,77,80,91,230,76.67,B,PASS
7,S008,Neha Joshi,CSE,95,93,91,94,279,93.00,A+,PASS
8,S009,Vivek Shah,IT,67,64,70,78,201,67.00,C,PASS
9,S010,Kavya Jain,CSE,84,80,82,89,246,82.00,A,PASS
10,S011,Arjun Rao,IT,72,75,69,82,216,72.00,B,PASS
11,S012,Simran Kaur,CSE,89,87,90,95,266,88.67,A,PASS
12,S013,Yash Malhotra,IT,61,59,63,70,183,61.00,C,PASS
13,S014,Isha Agarwal,CSE,78,81,76,87,235,78.33,B,PASS
14,S015,Karan Mishra,IT,55,52,57,68,164,54.67,D,PASS
15,S016,Riya Kapoor,CSE,91,94,89,97,274,91.33,A+,PASS
16,S017,Manish Yadav,IT,69,68,72,76,209,69.67,C,PASS
17,S018,Pooja Nair,CSE,83,86,84,90,253,84.33,A,PASS
18,S019,Dev Tiwari,IT,47,45,49,65,141,47.00,F,PASS
19,S020,Nisha Saxena,CSE,74,71,73,84,218,72.67,B,PASS

In [92]:
print("Number of Students:", len(df))
print("Number of Columns:", len(df.columns))
print("Column Names:")
print(df.columns.tolist())

Number of Students: 20
Number of Columns: 11
Column Names:
['Student_ID', 'Name', 'Department', 'Python', 'AI', 'Mathematics', 'Attendance', 'Total_Marks', 'Average_Marks', 'Grade', 'Result']

In [93]:
print("==========================================")
print("   STUDENT PERFORMANCE ANALYTICS SYSTEM")
print("==========================================")

print("Total Students        :", len(df))
print("Students Passed       :", pass_count)
print("Students Failed       :", fail_count)
print("Overall Class Average :", round(overall_average, 2))
print("Average Attendance    :", round(average_attendance, 2), "%")
print("Highest Total Marks   :", highest_total)
print("Lowest Total Marks    :", lowest_total)
print("Best Subject         :", best_subject["Subject"])
print("Weakest Subject      :", weakest_subject["Subject"])
print("==========================================")

==========================================
   STUDENT PERFORMANCE ANALYTICS SYSTEM
==========================================
Total Students        : 20
Students Passed       : 20
Students Failed       : 0
Overall Class Average : 75.22
Average Attendance    : 83.7 %
Highest Total Marks   : 279
Lowest Total Marks    : 141
Best Subject         : AI
Weakest Subject      : Python
==========================================